[package]
name = "rust-embedded"
version = "0.1.0"
authors = ["Andreas Arnold <andreas@featureenvy.com>"]
build = "build.rs"


[build-dependencies]
gcc = "0.3"

[dependencies]
rust-libcore = "*"

[dependencies.rlibc]
git = "https://github.com/hackndev/rlibc"
branch = "zinc"
